### ISSUE TITLE
模型替换为ppocrv3的模型，op不支持

### ISSUE THREAD

**Issue by zhang0227** [LZX284/PaddleOCR4Android#2]
将模型替换为ppocrv3的模型，会报io_copy 这个op不支持的错误，我替换了2.10版的libpaddle_api_light_bundled.a libpaddle_light_api_shared.so 后就变成报错Paddle-Lite: [F  6/17 10:55:56. 79 ...e-Lite/lite/model_parser/model_parser.cc:956 LoadModelNaiveFromMemory] The model format cannot be recognized. Please make sure you use the correct interface and model file.
模型为ppocr官网直接下载的v3 nb格式模型，预测库为2.10 release inference_lite_lib.android.armv8.gcc.c++_shared.with_extra.with_cv

**Comment by LZX284** [comment]
> 将模型替换为ppocrv3的模型，会报io_copy 这个op不支持的错误，我替换了2.10版的libpaddle_api_light_bundled.a libpaddle_light_api_shared.so 后就变成报错Paddle-Lite: [F 6/17 10:55:56. 79 ...e-Lite/lite/model_parser/model_parser.cc:956 LoadModelNaiveFromMemory] The model format cannot be recognized. Please make sure you use the correct interface and model file. 模型为ppocr官网直接下载的v3 nb格式模型，预测库为2.10 release inference_lite_lib.android.armv8.gcc.c++_shared.with_extra.with_cv

@zhang0227 当前版本基于PaddleOCR 2.4/PaddleLite 2.9，2.9与2.10的模型不是通用的，直接替换为ppocrv3的模型当然会报错。另外，要升级为PaddleLite 2.10 是可以的，只是不能简单的只替换其中几个文件，否则容易爆出各种不匹配的问题。

**Comment by qingweiSun** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/16513906/174753440-87434dd0-1b07-4fbb-9b13-655aa6d0f9c8.png">
我用的应该是2.0的，你的demo可以运行，但我拿到我的项目就不行
